### ISSUE TITLE
app.ServeDir only serves one file

### ISSUE THREAD

**Issue by ctalladen78** [gramework/gramework#33]
I have javascript files being referenced from the index file.  I was getting a 404 file not found from the browser console and upon further inspection it was because when I was referencing the directory, expecting all directory contents to be served, the index file was literally the only thing being served.

Any suggestions? Looks like fasthttp and gramework are good ideas and they are fast, but just not ready for gametime

Only a cool side hobby

**Comment by kirillDanshin** [comment]
hi @ctalladen78. Sorry for late reply.

I found your code [here](https://github.com/ctalladen78/GolangPushups/blob/master/gramework-example.go).

As you can see, you didn't used wildcard parameter that is *required* for ServeDir to work. When you call `app.GET("/somePath/*any", app.ServeDir("./somePath"))`. Notice that `*any` part of the route, that 'causes any route under `/somePath` in this case to be routed to the given handler.

Gramework is optimized for SPA (see `SPAIndex()`), but not for multipage template-based websites ("MTWS" further). That 'caused by default router based on fasthttprouter, that denies any routes conflicting with wildcards, so currently MTWS possible to implement, but gramework doesn't give you as many "shortcuts" for MTWS as for SPA. Anyway, we're working on it and support is planned in 1.2.0.

**Comment by ctalladen78** [comment]
yes my intent was to deliver a SPA with Golang. I will try again. good work I will monitor the progress
